Criado o module files e a resolver create File
ditointernet/tradulab pull request #11
Opened 2020-11-10 13:47 UTC by Wxhbr

[ ] - Criado module files

2020-11-16 13:02 UTC, andyboli commented on packages/api/src/modules/auth/resolvers.ts
> +    //  Duvidas sobre as linhas abaixo
remover comentátio

2020-11-19 17:15 UTC, miguel-miguelito requested changes

2020-11-19 17:15 UTC, miguel-miguelito commented on packages/api/src/modules/file/model.ts
> +    sourceLanguage: {
A gente podia fazer um enum com algumas possíveis linguagens (e depois ir aumentando essa lista), o que acham?

2020-11-19 17:15 UTC, miguel-miguelito commented on packages/api/src/modules/file/model.ts
> +// }
Por que isso está comentado? Não deu certo no typescript?

2020-11-19 17:15 UTC, miguel-miguelito commented on packages/api/src/modules/file/resolvers.ts
> +    throw new Error('File size exceeded, limit is 5MB.');
Pode trocar por ApolloError, e temos que definir um code pra esse erro (segundo parâmetro)

2020-11-19 17:15 UTC, miguel-miguelito commented on packages/api/src/modules/file/resolvers.ts
> +  // stream.on('data', (chunk) => console.log(chunk.toString()));
Apagar? Ou isso vai ser necessário mais tarde?

2020-11-19 17:15 UTC, miguel-miguelito commented on packages/api/src/modules/file/resolvers.ts
> +    throw new Error('The provided project does not exist.');
Sugiro substituir por `throw new ApolloError('The provided project does not exist.', 'PROJECT_NOT_FOUND');`

2020-11-19 17:15 UTC, miguel-miguelito commented on packages/api/src/modules/file/resolvers.ts
> +  } catch (err) {
Qual a diferença entre capturar ou não capturar o erro nesse caso?

2020-11-19 17:15 UTC, miguel-miguelito commented on packages/api/src/modules/file/types.ts
> +  scalar FileUpload
O que isso faz?

2020-11-19 17:15 UTC, miguel-miguelito commented on packages/web/src/UploadForm.tsx
> +    variables: { email: "uriell.viana@dito.com.br", password: "123456" },
Isso aqui era só teste né?

2020-11-23 12:47 UTC, Wxhbr commented on packages/api/src/index.ts
> +  console.log('ERROOOO', err);
Resolvido

2020-11-23 12:48 UTC, Wxhbr commented on packages/api/src/modules/file/resolvers.ts
> +  // stream.on('data', (chunk) => console.log(chunk.toString()));
Apagado

2020-11-23 12:49 UTC, Wxhbr commented on packages/api/src/middlewares/apollo.ts
>                isManagerOrOwner
Temos que conversar mais sobre isso, mas acredito que sim, somente manager ou owner e talvez developer pra poder convidar pra um projeto

2020-11-23 12:50 UTC, Wxhbr commented on packages/api/src/middlewares/apollo.ts
> +        user: undefined,
Respondido no remove file

2020-11-23 12:51 UTC, Wxhbr commented on packages/api/src/middlewares/apollo.ts
> +        contentLength: headers['content-length'],
Podemos conversar se mudar pra number vai ser melhor do que trabalhar com string, não tenho uma resposta nesse exato momento.

2020-11-23 12:52 UTC, Wxhbr commented on packages/api/src/modules/auth/resolvers.ts
> +    // Error sem estar na constant de error
Eu acho legal, mas vamos decidir isso.

2020-11-23 12:52 UTC, Wxhbr commented on packages/api/src/modules/file/model.ts
> +    sourceLanguage: {
Vamos conversar sobre isso. É uma boa ideia.

2020-11-23 12:52 UTC, Wxhbr commented on packages/api/src/modules/file/model.ts
> +// }
Resolvido e resposta no update file ou remove file

2020-11-23 12:53 UTC, Wxhbr commented on packages/api/src/modules/file/resolvers.ts
> +  } catch (err) {
se der alguma problema na hora de salvar a file não teria que enviar esse erro pra algum lugar?

2020-11-23 12:53 UTC, Wxhbr commented on packages/api/src/modules/file/types.ts
> +  scalar FileUpload
Explicado no update file ou remove file

2020-11-23 12:53 UTC, Wxhbr commented on packages/web/src/UploadForm.tsx
> +    variables: { email: "uriell.viana@dito.com.br", password: "123456" },
sim

2020-11-23 14:28 UTC, miguel-miguelito commented on packages/api/src/index.ts
> +  console.log('ERROOOO', err);
Uai, aqui continua aparecendo o console.log, vc deu push?

2020-11-23 14:28 UTC, miguel-miguelito commented on packages/api/src/middlewares/apollo.ts
>                isManagerOrOwner
É que a gente tinha feito toda aquela lógica de hierarquia de cargos

2020-11-23 19:08 UTC, Wxhbr commented on packages/api/src/index.ts
> +// import { graphqlUploadExpress } from 'graphql-upload';
Eu vou deixar só pra lembrar de qndo a gente for fazer createReadStream()

2020-11-24 20:12 UTC, miguel-miguelito approved these changes

2020-11-26 05:05 UTC, miguel-miguelito submitted a review, later dismissed

2020-11-26 18:04 UTC, andyboli approved these changes

2020-11-26 18:11 UTC, miguel-miguelito submitted a review, later dismissed

2020-11-26 18:11 UTC, andyboli submitted a review, later dismissed

2020-11-26 19:42 UTC, andyboli approved these changes

2020-11-26 19:51 UTC, miguel-miguelito requested changes

2020-11-26 19:51 UTC, miguel-miguelito commented on packages/api/src/index.ts
> +  console.error("Error: ", err.name)
Faltou aspas simples e ponto-e-vírgula

2020-11-26 19:51 UTC, miguel-miguelito commented on packages/api/src/middlewares/apollo.ts
> +      if (allowedRoles.includes(projectRole?.role)) return true;
Acho que o node 12 não suporta isso. Teria que ser:
`if (projectRole && allowedRoles.includes(projectRole.role))`

2020-11-26 19:51 UTC, miguel-miguelito commented on packages/api/src/middlewares/apollo.ts
> +)
Faltou ponto-e-vírgula

2020-11-26 19:51 UTC, miguel-miguelito commented on packages/api/src/modules/auth/model.ts
> +};
Não tenho certeza se o formatador coloca ponto-e-vírgula aqui

2020-11-26 19:51 UTC, miguel-miguelito commented on packages/api/src/modules/file/model.ts
> +};
Formatador não coloca ponto-e-vírgula aqui

2020-11-26 19:51 UTC, miguel-miguelito commented on packages/api/src/modules/file/resolvers.ts
> +import { model as File } from '.';
Essa importação tá certa??

2020-11-26 19:51 UTC, miguel-miguelito commented on packages/api/src/modules/role/constants.ts
> -// Array ordenado Hierarquicamente
Pode deixar esse comentário aqui

2020-11-26 19:51 UTC, miguel-miguelito commented on packages/api/src/modules/role/types.ts
> +# Por que esses diferentes tipos de Role... ?
Retirar comentário

2020-11-27 12:46 UTC, Wxhbr commented on packages/api/src/modules/file/resolvers.ts
> +import { model as File } from '.';
Ta correta, porque ele ta pegando o model File do index e o index importa os models todos.

2020-11-27 16:33 UTC, miguel-miguelito approved these changes

2020-11-30 13:15 UTC, andyboli submitted a review, later dismissed

2020-11-30 13:23 UTC, UriellViana requested changes

2020-11-30 13:23 UTC, UriellViana commented on packages/api/src/middlewares/apollo.ts
> +        contentLength: headers['content-length'],
Acredito que todo header vem como string, bota um parseInt, na dúvida um parseInt de number dá number tbm..

2020-11-30 13:23 UTC, UriellViana commented on packages/api/src/modules/auth/resolvers.ts
> +    //  Duvidas sobre as linhas abaixo
Yep, eu dei unresolve nisso pq continua ali

2020-11-30 23:26 UTC, UriellViana requested changes

2020-11-30 23:26 UTC, UriellViana commented on packages/api/src/middlewares/apollo.ts
> +        contentLength: headers['content-length'],
parseInt

2020-11-30 23:26 UTC, UriellViana commented on packages/api/src/modules/auth/resolvers.ts
> +    //  Duvidas sobre as linhas abaixo
remover comentário

2020-12-01 15:12 UTC, miguel-miguelito approved these changes

2020-12-02 12:36 UTC, andyboli approved these changes

2020-12-02 14:07 UTC, UriellViana submitted a review, later dismissed

2020-12-03 14:53 UTC, andyboli approved these changes

2020-12-04 12:03 UTC, miguel-miguelito approved these changes

2020-12-21 19:53 UTC, closed without merging