[Feature] Created removeFile resolver
ditointernet/tradulab pull request #22
Opened 2020-11-18 20:41 UTC by Wxhbr

- [ ] Created removeFile resolver

2020-11-20 17:13 UTC, miguel-miguelito requested changes

2020-11-20 17:13 UTC, miguel-miguelito commented on packages/api/src/modules/file/resolvers.ts
> +  const file = new File({
Você testou e deu certinho, salvou no banco? Porque tem um negócio no javascript que também se chama File e se usa com new File(), aí só pra saber se realmente ele interpretou que File é o model

2020-11-20 17:13 UTC, miguel-miguelito commented on packages/api/src/modules/file/resolvers.ts
> +    throw new Error('The provided file does not exist.');
Substituir Error por ApolloError

2020-11-20 17:13 UTC, miguel-miguelito commented on packages/api/src/modules/file/resolvers.ts
> +  newFilename: string;
Ficou combinado que seria possível mudar o nome do arquivo? Tô perguntando pq realmente não me lembro

2020-11-20 17:13 UTC, miguel-miguelito commented on packages/api/src/modules/file/model.ts
> +    filename: {
Ficou combinado que o nome do arquivo não precisa ser único?

2020-11-20 17:13 UTC, miguel-miguelito commented on packages/api/src/modules/file/resolvers.ts
> +    throw new Error('The provided file does not exist.');
Substituir Error por ApolloError

2020-11-20 17:13 UTC, miguel-miguelito commented on packages/api/src/modules/file/resolvers.ts
> +  return resp;
Poderia também retornar um booleano em vez de string

2020-11-23 12:08 UTC, Wxhbr commented on packages/api/src/modules/file/resolvers.ts
> +  const file = new File({
Está salvando corretamente no banco de dados

2020-11-23 12:10 UTC, Wxhbr commented on packages/api/src/modules/file/resolvers.ts
> +  newFilename: string;
Falamos que iria poder mudar o nome em alguma reunião não lembro e caso queira ver um pouco mais sobre o que foi discutido tem uma thread no slack(Duvidas sobre updateFile) que eu e uriell conversamos sobre o que falta no updateFile.

2020-11-23 12:13 UTC, Wxhbr commented on packages/api/src/modules/file/model.ts
> +    filename: {
Acredito que talvez dentro de um mesmo projeto eles podem ser únicos, mas no contexto geral da aplicação não. Nesse caso que o banco ta salvando todas as files da aplicação toda, não teria sentido deixar único porque em projetos diferentes podem ter arquivos com nomes iguais, faz sentindo?

2020-11-23 12:15 UTC, Wxhbr commented on packages/api/src/modules/file/resolvers.ts
> +  return resp;
Poderia sim, não tratei essa parte direito. Minha duvida é se o usuario vai receber algum feedback vindo do backend que foi removido com sucesso ou só o true mesmo.

2020-11-23 17:47 UTC, miguel-miguelito approved these changes

2020-11-23 17:47 UTC, miguel-miguelito commented on packages/api/src/modules/file/model.ts
> +    filename: {
É que eu lembro que a gente tinha discutido sobre deixar o nome do arquivo como um id, mas não lembro qual foi a conclusão

2020-11-23 17:47 UTC, miguel-miguelito commented on packages/api/src/modules/file/resolvers.ts
> +  return resp;
Qualquer coisa a gente muda depois

2020-11-26 17:53 UTC, andyboli approved these changes

2021-01-28 12:21 UTC, closed without merging