Create Web and API Images, and the Volume
ditointernet/tradulab pull request #23
Opened 2020-11-18 22:00 UTC by andyboli

2020-11-19 11:14 UTC, Wxhbr reviewed
Depois gostaria que me explicasse como funciona essa parte de volume do docker por favor

2020-11-21 14:25 UTC, UriellViana requested changes

2020-11-21 14:25 UTC, UriellViana commented on packages/api/Dockerfile
> +FROM node:latest
não pode ser latest, pq sempre q lançar uma versão nova do node ja vai pegar ela e não necessariamente estamos prontos pra suportar todas, sugiro a 12 estática aqui..

uma coisa boa de docker é que tem imagens menores chamadas -stretch, então sugiro a `node:12-stretch`

2020-11-21 14:25 UTC, UriellViana commented on packages/web/Dockerfile
> +FROM node:latest
mesma coisa aqui

2020-11-25 11:48 UTC, Wxhbr requested changes

2020-11-25 11:48 UTC, Wxhbr commented on packages/api/src/index.ts
> +console.log("Bolivar")
Log desnecessario

2020-11-25 11:48 UTC, Wxhbr commented on packages/api/src/modules/auth/types.ts
> +    password: String! 0
Acho que tem um 0 solto no final da linha

2020-11-27 13:16 UTC, Wxhbr submitted a review, later dismissed

2020-12-02 14:09 UTC, UriellViana requested changes

2020-12-02 14:09 UTC, UriellViana commented on docker-compose.yml
> +      - tradulab:/var/lib/db
Acho que não precisa do volume pro db não, a gente quer um volume pra API salvar os files

2020-12-02 14:09 UTC, UriellViana commented on packages/api/src/modules/auth/resolvers.ts
> +    //  Duvidas sobre as linhas abaixo
Quais as dúvidas?

2020-12-02 22:59 UTC, UriellViana submitted a review, later dismissed

2020-12-03 15:29 UTC, Wxhbr commented on packages/web/src/Agenda.tsx
> +};
Isso era pra ta aqui msm?

2020-12-03 21:17 UTC, Wxhbr approved these changes

2020-12-04 12:16 UTC, miguel-miguelito requested changes

2020-12-04 12:16 UTC, miguel-miguelito commented on docker-compose.yml
> +<<<<<<< HEAD
Precisa resolver esse conflito

2020-12-04 12:16 UTC, miguel-miguelito commented on packages/api/src/modules/file/resolvers.ts
> +  // return file;
Código comentado

2020-12-04 12:16 UTC, miguel-miguelito commented on packages/web/src/App.tsx
> +// });
Código comentado

2020-12-04 12:16 UTC, miguel-miguelito commented on packages/web/src/UploadForm.tsx
> +// `
Código comentado

2020-12-04 12:16 UTC, miguel-miguelito commented on packages/web/src/UploadForm.tsx
> +  // if (data) console.log(data.login.token)
Código comentado

2020-12-21 19:42 UTC, Wxhbr approved these changes

2020-12-21 19:46 UTC, miguel-miguelito approved these changes

2020-12-21 19:49 UTC, roger067 requested changes

2020-12-21 19:49 UTC, roger067 commented on packages/api/src/index.ts
> -
por que removeu esse espaço dos imports?

2020-12-21 19:49 UTC, roger067 commented on packages/web/src/Agenda.tsx
> +import React from "react";
não entendi esse arquivo

2020-12-21 20:43 UTC, closed without merging