[Feature] List Files
ditointernet/tradulab pull request #28
Opened 2020-11-24 17:56 UTC by andyboli

2020-11-27 15:10 UTC, Wxhbr reviewed
Eu acho que deveriamos mergear a branch de error e do docker e do create file antes de mergear essa branch de qualquer forma.

2020-11-27 15:10 UTC, Wxhbr commented on packages/api/src/modules/file/resolvers.ts
> +
Acho que precisa de  um try catch? pq se o banco der problema aqui ele n vai capturar erro.

2020-11-27 15:10 UTC, Wxhbr commented on packages/api/src/modules/file/resolvers.ts
> +}
Quando nao encontra nenhuma file o retorno já não é um array vazio?

2020-11-27 15:10 UTC, Wxhbr commented on packages/api/src/modules/project/model.ts
>    this.slug = slug(this.displayName);
Essse comentario vai ser retirado?

2020-11-30 13:16 UTC, andyboli commented on packages/api/src/modules/file/resolvers.ts
> +}
Não, é um undefined

2020-11-30 13:25 UTC, andyboli commented on packages/api/src/modules/file/resolvers.ts
> +
Pensei nisso, porém observe o Create File, o file também é definido fora do Try, podemos usar esta abordagem https://stackoverflow.com/questions/9551020/accessing-variable-inside-try-catch . Mas para isso temos que alinhar como vamos tratar os erros, seria bom integrar isso com o PR do Miguel

2020-12-01 12:01 UTC, Wxhbr approved these changes

2020-12-03 14:56 UTC, andyboli commented on packages/api/src/modules/role/types.ts
>      role: String!
Perfeito @Wxhbr  explicação maravilhosa

2020-12-04 12:40 UTC, miguel-miguelito requested changes

2020-12-04 12:40 UTC, miguel-miguelito commented on packages/api/src/errors/index.ts
> +}
Ficou bacana

2020-12-04 12:40 UTC, miguel-miguelito commented on packages/api/src/middlewares/apollo.ts
> +const isAuthenticated = rule()((_, __, { user }) => {
Deixa os nomes antigos, mas com um _ na frente, por exemplo _parent, _args. Isso ajuda no entendimento de que parâmetros são esses caso a gente precise mudar o código.

2020-12-04 12:40 UTC, miguel-miguelito commented on packages/api/src/middlewares/apollo.ts
> +  rule()(async (_, { projectId }, { user: { id: currentUserId } }) => {
Deixa os nomes antigos, mas com um _ na frente, por exemplo _parent, _args. Isso ajuda no entendimento de que parâmetros são esses caso a gente precise mudar o código.

2020-12-04 12:40 UTC, miguel-miguelito commented on packages/api/src/modules/auth/resolvers.ts
> +async function createUser(_, args) {
Deixa os nomes antigos, mas com um _ na frente, por exemplo _parent, _args. Isso ajuda no entendimento de que parâmetros são esses caso a gente precise mudar o código.

2020-12-04 12:40 UTC, miguel-miguelito commented on packages/api/src/modules/auth/resolvers.ts
> +async function login(_, args) {
Deixa os nomes antigos, mas com um _ na frente, por exemplo _parent, _args. Isso ajuda no entendimento de que parâmetros são esses caso a gente precise mudar o código.

2020-12-04 12:40 UTC, miguel-miguelito commented on packages/api/src/modules/file/resolvers.ts
> +    throw new TradulabError('File size exceeded, limit is 5MB.');
Aqui é necessário o code da mensagem de erro.

2020-12-04 12:40 UTC, miguel-miguelito commented on packages/api/src/modules/file/types.ts
> +// Acho que o progress pode ser colocado no futuro, pois ele vai ser mais complexo que isso, progress de translation para qual lingua?
Temos que decidir se vamos retirar o progresso por enquanto para o MVP, e apagar comentário

2020-12-04 12:40 UTC, miguel-miguelito commented on packages/api/src/modules/project/resolvers.ts
> +async function createProject(_, args, context) {
Deixa os nomes antigos, mas com um _ na frente, por exemplo _parent, _args. Isso ajuda no entendimento de que parâmetros são esses caso a gente precise mudar o código.

2020-12-04 12:40 UTC, miguel-miguelito commented on packages/api/src/modules/project/resolvers.ts
> +// Não estamos tratando o Erro do roles.exect(), conflito com tipagem
Não entendi, explica isso melhor

2020-12-04 12:40 UTC, miguel-miguelito commented on packages/api/src/modules/project/resolvers.ts
> +async function myProjects(_, __, context) {
Deixa os nomes antigos, mas com um _ na frente, por exemplo _parent, _args. Isso ajuda no entendimento de que parâmetros são esses caso a gente precise mudar o código.

2020-12-04 12:40 UTC, miguel-miguelito commented on packages/api/src/modules/role/types.ts
> +# Por que esses diferentes tipos de Role... ?
Apagar comentário

2020-12-21 20:43 UTC, closed without merging