[Hotfix - BackEnd]
ditointernet/tradulab pull request #43
Opened 2020-12-15 02:21 UTC by andyboli

2020-12-16 16:48 UTC, miguel-miguelito requested changes

2020-12-16 16:48 UTC, miguel-miguelito commented on packages/web/src/Agenda.tsx
> +import React from "react";
Pode apagar esse arquivo.

2020-12-16 16:48 UTC, miguel-miguelito commented on packages/web/src/App.tsx
> +>>>>>>> feature/resolver-list-file
Tem conflitos pra resolver aqui

2020-12-16 16:48 UTC, miguel-miguelito commented on packages/web/src/UploadForm.tsx
> +>>>>>>> feature/resolver-list-file
Conflito

2020-12-16 16:48 UTC, miguel-miguelito commented on packages/web/src/UploadForm.tsx
> +>>>>>>> feature/resolver-list-file
Conflito

2020-12-16 16:48 UTC, miguel-miguelito commented on packages/web/src/UploadForm.tsx
> +>>>>>>> feature/resolver-list-file
Conflito

2020-12-16 16:48 UTC, miguel-miguelito commented on packages/web/src/UploadForm.tsx
> +>>>>>>> feature/resolver-list-file
Conflito

2020-12-21 11:46 UTC, Wxhbr approved these changes

2020-12-21 17:05 UTC, Wxhbr submitted a review, later dismissed

2020-12-21 18:29 UTC, miguel-miguelito submitted a review, later dismissed

2020-12-21 20:55 UTC, roger067 submitted a review, later dismissed

2020-12-22 11:21 UTC, Wxhbr submitted a review, later dismissed

2020-12-22 12:57 UTC, miguel-miguelito approved these changes

2020-12-22 13:49 UTC, miguel-miguelito approved these changes

2020-12-22 13:51 UTC, Wxhbr approved these changes

2020-12-22 13:51 UTC, merged