[Feature] Login
ditointernet/tradulab pull request #50
Opened 2020-12-28 13:20 UTC by andyboli

2020-12-28 14:31 UTC, andyboli commented
O background do Login é temporário até pensarmos algo melhor....

2021-01-04 12:11 UTC, miguel-miguelito requested changes
Fiz alguns comentários ao longo do código sobre o componente em si. Porém acho que você vai precisar abrir uma nova branch a partir da master, porque tem um monte de arquivo de outras branches aqui.

2021-01-04 12:11 UTC, miguel-miguelito commented on packages/web/src/components/LoginForm.tsx
> +  const passwordFilled = password.value == "" ? false : true;
Não precisava do ternário aqui. Basta fazer por exemplo:

`const emailError = Boolean(email.error)`

Mas também acho que nem precisava transformar em booleano explicitamente, o javascript ia interpretar assim

2021-01-04 12:11 UTC, miguel-miguelito commented on packages/web/src/components/LoginForm.tsx
> +        onClick={() => handleRegister()}
Pode colocar apenas handleRegister, sem arrow function

2021-01-04 12:11 UTC, miguel-miguelito commented on packages/web/src/components/Message/message.css
> +.Message {
Acho que tem como usar classes de css usando o próprio material-ui, tipo o que o Julio fez. Mas fica a seu critério.

2021-01-04 12:11 UTC, miguel-miguelito commented on packages/web/src/containers/pages/Login.tsx
> +        "string.pattern.base": "Password must contain at least 6 numbers",
Não lembro como a gente definiu isso no back-end. Mas tô achando bem esquisito precisar de 6 números e permitir outras letras. Talvez seja melhor só precisar de 6 letras num geral.

2021-01-04 13:50 UTC, Wxhbr approved these changes

2021-01-04 17:48 UTC, roger067 requested changes

2021-01-04 17:48 UTC, roger067 commented on packages/web/src/components/LoginForm.tsx
> +        onClick={() =>
Já que tem um form encapsulando o button é bom botar o handleLogin no onSubmit do form para que o usuário consiga logar ao clicar no Enter

2021-01-04 17:48 UTC, roger067 commented on packages/web/src/components/Message/message.css
> +.Message {
acho bom evitar arquivos css e padronizar com o material-ui

2021-01-07 13:19 UTC, roger067 requested changes

2021-01-07 13:19 UTC, roger067 commented on packages/web/src/components/LoginForm.tsx
> +        error={emailError}
não precisa criar as constants, só passar email.error já funcionaria

2021-01-13 13:06 UTC, Wxhbr requested changes

2021-01-13 18:32 UTC, Wxhbr approved these changes

2021-01-15 15:28 UTC, miguel-miguelito approved these changes

2021-01-18 11:15 UTC, Wxhbr approved these changes

2021-01-18 13:57 UTC, roger067 approved these changes

2021-01-18 21:47 UTC, andyboli commented
Branch em desuso devido histórico de commits confuso, alteração passadas para a branch feature/login-cleaned-up-branch #60

2021-01-18 21:47 UTC, andyboli commented
Branch em desuso devido histórico de commits confuso, alteração passadas para a branch feature/login-cleaned-up-branch #60

2021-01-18 21:47 UTC, closed without merging