[Feature] Create resolver update file
ditointernet/tradulab pull request #53
Opened 2021-01-14 13:36 UTC by Wxhbr

2021-01-17 23:25 UTC, andyboli requested changes

2021-01-17 23:25 UTC, andyboli commented on packages/api/src/modules/file/resolvers.ts
> +async function updateFile(_parent, args: IUpdateFileArgs) {
E a questão das roles? Qualquer um pode atualizar um arquivo? Para isso é só você acrescentar e trazer do contexto a role do usuário, no momento acho que que só é levado o id (auth.id) para os resolvers.

2021-01-19 17:33 UTC, miguel-miguelito commented on packages/api/src/modules/file/constants.ts
> +  FILE_DOESNT_EXIST: 'FILE_DOESNT_EXIST',
Não seria melhor manter o padrão e colocar 'FILE_NOT_FOUND' ?

2021-01-19 17:33 UTC, miguel-miguelito commented on packages/api/src/modules/file/resolvers.ts
>      throw new TradulabError('File size exceeded, limit is 5MB.');
Seria bom criar um code para isso também, mantendo o padrão

2021-01-21 13:11 UTC, UriellViana approved these changes

2021-01-21 14:59 UTC, miguel-miguelito approved these changes

2021-01-21 21:43 UTC, andyboli approved these changes

2021-01-21 21:43 UTC, andyboli commented on packages/api/src/middlewares/apollo/permissions.ts
> +      updateFile: isAuthenticated,
Em outra PR você vai criar as rules de Roles, correto?

2021-01-21 21:43 UTC, andyboli commented on packages/api/src/modules/file/model.ts
> +      required: false,
Por que o filePath é opicional?

2021-01-21 21:55 UTC, Wxhbr commented on packages/api/src/middlewares/apollo/permissions.ts
> +      updateFile: isAuthenticated,
Sim

2021-01-21 21:56 UTC, Wxhbr commented on packages/api/src/modules/file/model.ts
> +      required: false,
Pq é só pra testar e nao ficar pedindo file path nas request, então deixei ele opcional ate a gente ter de fato uma forma de pegar esse caminho de algum lugar.

2021-01-21 21:59 UTC, merged