[Feature] Login
ditointernet/tradulab pull request #60
Opened 2021-01-18 21:46 UTC by andyboli

Nova branch criada a partir da master e acrescentando as funcionalidades da branch feature/router, organizando o histórico de commits

2021-01-18 23:22 UTC, UriellViana requested changes

2021-01-18 23:22 UTC, UriellViana commented on packages/web/src/components/LoginForm.tsx
> +  const passwordFilled = Boolean(password.value);
Muito espaçamento entre essas constants, porém dá pra abolir a maior parte delas fazendo assim:

```js
!!email.error
!!password.error
!!email.value
!!password.value
```

Faz isso nos lugares que usam essas constants e dá na mesma.

2021-01-18 23:24 UTC, UriellViana requested changes
:pepelaugh:

2021-01-18 23:24 UTC, UriellViana commented on packages/api/package.json
> +    "@hapi/joi": "17.1.1",
Vi que vc usa o Joi no front end mas instalou o package na API

2021-01-19 13:35 UTC, UriellViana approved these changes

2021-01-19 17:28 UTC, miguel-miguelito approved these changes

2021-01-19 20:08 UTC, Wxhbr approved these changes

2021-01-19 20:36 UTC, merged