[Feature] Criar o resolver rateSuggestion
ditointernet/tradulab pull request #65
Opened 2021-01-26 03:00 UTC by miguel-miguelito

2021-01-26 13:36 UTC, andyboli commented on packages/api/src/modules/suggestion/resolvers.ts
> +    (vote === 'positive' && curPositiveArr.includes(user)) ||
Acho que deveria separ em uma constante essa lógica para ficar mais descritivo, sugiro o nome **hasPositiveRate** ou **hasPositiveVote** se quiser seguir a linha de vote, eu acho melhor substituir vote por rate.

2021-01-26 13:36 UTC, andyboli commented on packages/api/src/modules/suggestion/resolvers.ts
> +    (vote === 'negative' && curNegativeArr.includes(user)) ||
Acho que deveria separ em uma constante essa lógica para ficar mais descritivo, sugiro o nome **hasNegativeRate** ou **hasNegativeVote** se quiser seguir a linha de vote, eu acho melhor substituir vote por rate.

2021-01-26 14:07 UTC, UriellViana requested changes

2021-01-26 14:07 UTC, UriellViana commented on packages/api/src/modules/suggestion/resolvers.ts
> +    (vote === 'positive' && curPositiveArr.includes(user)) ||
Pelo que eu entendi:

- Se eu já votei positivo, e voto positivo novamente, remove..
- Se eu já votei positivo, e voto negativo, remove..
- Se eu não votei positivo, ou votei negativo, adiciona o positivo..

Parece um pouco complexo de compreender, sugiro a gente possibilitar o `vote` de vir nulo/undefined, significando a remoção do voto. Se a pessoa já votou, e mandou outro voto, não faz nada.

2021-01-26 17:09 UTC, miguel-miguelito commented on packages/api/src/modules/suggestion/resolvers.ts
> +    (vote === 'positive' && curPositiveArr.includes(user)) ||
@UriellViana Cheguei a pensar nisso de vir nulo, mas acabei fazendo assim pensando que seria mais fácil para o front-end não ter que se preocupar com a situação de cada clique. Tipo, funcionar como um toggle. Mas realmente, acho que fica mais explícito desse jeito que você sugeriu.

2021-01-26 17:09 UTC, miguel-miguelito commented on packages/api/src/modules/suggestion/resolvers.ts
> +    (vote === 'positive' && curPositiveArr.includes(user)) ||
Eu devo mudar essa lógica com a sugestão do Uriell

2021-01-26 17:09 UTC, miguel-miguelito commented on packages/api/src/modules/suggestion/resolvers.ts
> +    (vote === 'negative' && curNegativeArr.includes(user)) ||
Eu devo mudar essa lógica com a sugestão do Uriell

2021-01-28 17:02 UTC, andyboli requested changes

2021-01-28 17:02 UTC, andyboli commented on packages/api/src/modules/suggestion/resolvers.ts
> +  vote: 'positive' | 'negative' | 'clear';
Muito estranho ter um 'clear', percebe que a inteção dele é diferente dos demais ? Eu particularmente acho estranho.

2021-01-28 17:02 UTC, andyboli commented on packages/api/src/modules/suggestion/resolvers.ts
> +  vote: 'positive' | 'negative' | 'clear';
Como disse, acho que essa lógica deveria ficar no front, pois ele deve saber o que enviar no request quando já deu like ou não, até pq o botão esta no front, eu penso assim...

2021-01-28 17:02 UTC, andyboli commented on packages/api/src/modules/suggestion/resolvers.ts
> +      }
Talvez esteja complexo demais para um objetivo simples que é salvar o voto do usuário

2021-01-28 17:18 UTC, miguel-miguelito commented on packages/api/src/modules/suggestion/constants.ts
> +  CONTRADICTORY_RATING: 'You cannot upvote e downvote the same suggestion.',
Discordo. Acho que também é dever do back-end barrar umas coisas estranhas assim. Tipo, igual o Uriell falou em outro comentário, acho de boa simplesmente não acontecer nada caso a pessoa enviar um voto positivo sendo que ela já votou positivo. Mas votar positivamente sem antes desfazer o voto negativo já acho estranho demais, dado que tem uma opção "clear".

Tipo, tem uns erros que a gente coloca no back-end (esse por exemplo) que é só para reforçar que coisas estranhas não vão acontecer. Ainda continua sendo principal (na minha opinião) o dever do front-end de desabilitar o clique caso a pessoa já tenha feito uma avaliação oposta.

2021-01-28 17:25 UTC, miguel-miguelito commented on packages/api/src/modules/suggestion/resolvers.ts
> +  vote: 'positive' | 'negative' | 'clear';
Que nem falei no outro comentário, acho que tanto o front quanto o back tem que impedir que coisas estranhas aconteçam. 

Sobre o "clear", tbm não sei se foi a melhor escolha. Eu segui o que o Uriell sugeriu de ter opção positive/negative/null. Mas achei estranho demais uma string "null", e por isso coloquei "clear", para ficar até mais semântico conforme a intenção do "voto".

2021-01-28 17:27 UTC, miguel-miguelito commented on packages/api/src/modules/suggestion/resolvers.ts
> +      }
A questão é que dois arrays com votos, e tem que verificar cada array para não adicionar votos repetidos ou contraditórios.

2021-01-28 22:45 UTC, UriellViana approved these changes

2021-01-28 22:52 UTC, andyboli approved these changes

2021-01-28 23:09 UTC, merged